# Generated by iptables-save v1.8.10 (nf_tables) on Sat Nov  8 16:20:43 2025
*filter
:INPUT DROP [50:4665]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -s 192.168.56.11/32 -p tcp -m tcp --dport 8080 -j ACCEPT
COMMIT
# Completed on Sat Nov  8 16:20:43 2025
